name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: ':sparkles: Features'
    label: 'feature'
  - title: ':bug: Bug Fixes'
    label: 'fix'
  - title: ':construction: Maintenance'
    labels:
      - 'docs'
      - 'refactor'
      - 'test'
  - title: ':rocket: Improvements'
    labels:
      - 'ci'
      - 'build'
      - 'performance'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed

  $CHANGES
